config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :posts
  root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
	validates :title, presence: true, length: { minimum: 5 }
	validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

	def index
		@posts = Post.all.order('created_at DESC')
	end

	def new
		@post = Post.new
	end

	def create
		@post = Post.new(post_params)

		if @post.save
			redirect_to @post
		else
			render 'new'
		end
	end

	def show
		@post = Post.find(params[:id])
	end

	private

		def post_params
			params.require(:post).permit(:title, :body)
		end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tumblr</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    'application', 'https://fonts.googleapis.com/css?family=Raleway' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag 'favicon.ico' %>
  </head>

  <body>
  	<div id="sidebar">
  		<ul>
  			<li class="category"><%= link_to "Tumblr", root_path %></li>
  			<li><%= link_to "Posts", root_path %></li>
  			<li>About</li>
  		</ul>

  		<p class="sign_in">User Login</p>
  	</div>


  	<div id="main_content">
  		<div id="header">
  			<p>Post Feed</p>
  			<div class="buttons">
  				<button class="button"><%= link_to "Make Post", new_post_path %></button>
  				<button class="button">Log Out</button>
  			</div>
  		</div>

	  	<% flash.each do |name, msg|%>
	  		<%= content_tag(:div, msg, class: "alert")%>
	  	<% end %>

	    <%= yield %>
  	</div>

  </body>
</html>

app/views/posts/index.html.erb
<% @posts.each do |post| %>
	<div class="post_wrapper">
		<h2 class="title"><%= link_to post.title, post %></h2>
		<p class="body"><%= truncate(post.body, length:100)%></p>
		<p class="date"><%= time_ago_in_words(post.created_at) %> </p>
	</div>
<%end %>

app/views/posts/new.html.erb
<div id="page_wrapper">
	<h1>Make Something</h1>

	<%= form_for :post, url: posts_path do |f| %>
		<% if @post.errors.any? %>
			<div id="errors">
				<h2><% pluralize(@post.errors.count, "error") %> Stoped this post from saving </h2>
				<ul>
					<% @post.errors.full_messages.each do |msg| %>
						<li><%= msg %></li>
					<% end %>
				</ul>
			</div>
		<% end%>

		<p>
			<%= f.label :title %><br>
			<%= f.text_field :title %>
		</p>

		<p>
			<%= f.label :body %><br>
			<%= f.text_area :body %>
		</p>

		<p>
			<%= f.submit %>
		</p>

	<% end %>
</div>

app/views/posts/show.html.erb
<div id="post_content">
	<h1 class="title">
		<%= @post.title %>
	</h1>

	<p class="date">
		Submitted <%= time_ago_in_words(@post.created_at) %> ago
	</p>

	<p class="body">
		<%= @post.body %>
	</p>
</div>